# Generated by Django 6.1.1 on 2026-10-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, help_text='Menu section, e.g. Biryani or Desserts', max_length=60),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.CharField(blank=True, help_text='Static file path, e.g. img/food/biryani.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=False, verbose_name='Vegetarian'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='area',
            field=models.CharField(blank=True, choices=[('Kozhikode', [('mananchira', 'Mananchira'), ('nadakkavu', 'Nadakkavu'), ('beach-road', 'Beach Road'), ('thondayad', 'Thondayad'), ('feroke', 'Feroke')]), ('Kannur', [('fort-road', 'Fort Road'), ('thavakkara', 'Thavakkara'), ('thana', 'Thana'), ('payyambalam', 'Payyambalam')]), ('Bengaluru', [('koramangala', 'Koramangala'), ('indiranagar', 'Indiranagar'), ('hsr-layout', 'HSR Layout'), ('btm-layout', 'BTM Layout'), ('mg-road', 'MG Road'), ('whitefield', 'Whitefield')])], help_text='Sets the city and the map position.', max_length=40),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover_image',
            field=models.CharField(blank=True, help_text='Static file path, e.g. img/food/biryani.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(blank=True, help_text='For example: Malabar, Biryani', max_length=80),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=1, default=6, max_digits=4),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Leave empty to use the centre of the area.', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='prep_minutes',
            field=models.PositiveSmallIntegerField(default=20, help_text='Typical kitchen time for an order.'),
        ),
    ]
